baseURL: https://webfinger.net
title: WebFinger

markup:
  goldmark:
    extensions:
      linkify: true
    renderer:
      unsafe: true

# disable taxonomies
taxonomies: []

outputs:
  home: [html]
  section: [html]
